### ISSUE TITLE
Problems with Oregon data?

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/issues#134]
Saw this on Twitter: https://twitter.com/kms_sf/status/1245834999376445440.

I looked into the screenshots for 3/29 - 4/2. All the numbers look correct except for some sampling issues on 3/30 - 4/1. I don't think there are any corrections to be made but happy to have a second pair of eyes on the data.

**Comment by muamichali** [comment]
<img width="280" alt="OR Positives Before" src="https://user-images.githubusercontent.com/1749380/78455045-0de5db00-766a-11ea-82e0-22801474b8be.png">

<img width="207" alt="OR Positives After" src="https://user-images.githubusercontent.com/1749380/78455047-11796200-766a-11ea-8140-250129f8af79.png">

I re-checked the screenshots and found that two dates had the same number. I fixed in States Daily. Screenshots above.
