### ISSUE TITLE
Daily new case is wildly different from state site

### ISSUE THREAD

**Issue by bibhas2** [COVID19Tracking/issues#138]
I'm seeing great difference in **daily new case** data for FL when compared to the official site:

https://experience.arcgis.com/experience/96dd742462124fa0b38ddedb9b25e429

For example:

Date: 04/02/2020
FL site: 1.3K
API positiveIncrease: 1055

Date: 04/01/2020
FL site: 1.1K
API positiveIncrease: 617

**Comment by jdmaresco** [comment]
@olivierlacan can you take a look at this?

**Comment by bibhas2** [comment]
Please let me know if I can do something.

**Comment by olivierlacan** [comment]
Case dates are routinely back-filled resulting in updates to this daily delta bar chart (which I’m guessing you’re using as a source here) when they’re processed by FDOH so their daily delta will change over time whereas we capture the daily state of total positives, negatives, and pending cases each day so we’re bound to have fewer if they retroactively add cases that were first processed (by their definition I believe it’s when the positive test first came back). 

The more tests are done the more they’ll have a backlog. There’s not much we can do other than re-create time series aggregates (cases grouped by day of diagnosis) but even that is imperfect because patients who die don’t die on the day of their diagnosis which is all the Florida data gives as far as dates. 

As methodology goes the two methods are valid. We’re capturing **known cases** on any given day. FDOH is doing that too but adding and removing cases (erroneously counted deaths or false positives that are later removed) to previously released data.

**Comment by bibhas2** [comment]
How NY Times data compares for the same two dates.

```
Date: 04/02/2020
FL site: 1.3K
NYT: 1235
API positiveIncrease: 1055

Date: 04/01/2020
FL site: 1.1K
NYT: 1024
API positiveIncrease: 617
```
