### ISSUE TITLE
Some positive/negative anomalies

### ISSUE THREAD

**Issue by gitjeff05** [COVID19Tracking/issues#187]
While working on [tests for cumulative (+/-) values](https://github.com/COVID19Tracking/website/pull/510), I encountered 4 anomalies in [States Historical Data](https://covidtracking.com/api). There are some cumulative entries that are *less than* the value for previous date. This should never happen if values are cumulative.

I know the state websites are the "source of truth" but anomalies like this suggest that their public websites may have experienced a sort of regression and I wonder if we shouldn't correct it or seek clarification? Anyways, I thought I would open the issue to at least document these somewhere:

**RI**

```json
{
  "date": 20200306,
  "positive": 3,
},
{
  "date": 20200305,
  "positive": 2
}
```

**WY**

```json
{
  "date": 20200411,
  "positive": 261
},
{
  "date": 20200410,
  "positive": 320
}
```

**DE**

```json
{
  "date": 20200411,
  "negative": 9624
},
{
  "date": 20200410,
  "negative": 10415
}
```

**WI**

```json
{
  "date": 20200330,
  "negative": 15856
},
{
  "date": 20200329,
  "negative": 16550
}
```

**Comment by gitjeff05** [comment]
In the case Delaware, it appears that it may have been a regression on their part. Does the recorder take the highest value if there are multiple values for positive/negative on a single day?

**Comment by karaschechtman** [comment]
Hi @gitjeff05,
Thanks for pointing these discrepancies out! 

WI and DE: Since these numbers come directly from the states according to historical screenshots ([DE](https://covidtracking.com/screenshots/DE/DE-20200411-180500.png) + [WI](https://covidtracking.com/screenshots/WI/WI-20200330-181607.png)), we are going to leave as is and make a public note that the states revised down.
WY: data on positives for 4/10 was a data entry mistake corrected down to 253 on 4/18, which fixed the problem.
![Screen Shot 2020-05-11 at 11 03 17 AM](https://user-images.githubusercontent.com/15933271/81585303-f644f500-9381-11ea-87e3-c680d60b435f.png)
RI: there are no historical screenshots to investigate this data, so I think we should leave it as is.
