### ISSUE TITLE
NUmbers are very wrong

### ISSUE THREAD

**Issue by Spielmadchen** [COVID19Tracking/issues#214]
Your numbers have been vastly different from the ones at worldometer.

https://www.worldometers.info/coronavirus/country/us/

**Comment by catawbasam** [comment]
possibly related: "On April 14, New York City reported 3,778 additional deaths that have occurred since March 11 and have been classified as "probable," defined as follows: “decedent [...] had no known positive laboratory test for SARS-CoV-2 (COVID-19) but the death certificate lists as a cause of death “COVID-19” or an equivalent" [source]. 

From April 14 onward, New York City has provided - and will continue to provide -  the updated number of probable deaths in its daily reports."

See also the new issue about changes in CDC reporting guidance, why now includes probable deaths and not just confirmed.

**Comment by muamichali** [comment]
Yes, @catawbasam Thanks for responding here. The numbers that NYC added in bulk on 4/14 are not reflected in our daily reports.
