### ISSUE TITLE
Deaths: Confirmed vs. probable, new CDC guideline

### ISSUE THREAD

**Issue by datadict** [COVID19Tracking/issues#215]
Dear team,

It seems like CDC has updated their guidelines how to count deaths. They want probable deaths (no laboratory confirmation required) added to the confirmed deaths. 

How will you continue to report your numbers: Incl. probable deaths or excl. probable deaths? And if you plan to include it, how do you go about New York's 3,778 probable deaths, that are not allocated to specific dates yet?

Thanks,
Patrick

**Comment by muamichali** [comment]
Thanks, Patrick! 

We are discussing how to handle the probable deaths as its own metric.
 
For now, we are including public notes about each state where the probable deaths are included and we do include the probable deaths within the overall deaths. See for example Puerto Rico's note here https://covidtracking.com/data#state-pr

![PR](https://user-images.githubusercontent.com/1749380/79639222-587e5180-8158-11ea-8c6c-79358d44ba6f.PNG)

**Comment by patrickmitschka** [comment]
Michal,

Thank you for your quick and helpful reply!

That makes sense! Would it be fair to say that most states still report “confirmed” only (also when they do not comment on it)?

FYI: Other than for Puerto Rico, I saw that New York publishes separate figures (https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-deaths-confirmed-probable-daily-04152020.pdf). As far as I am aware, these deaths cannot be fully allocated to specific days, so for my analysis I excluded these to not mess up the growth rates.

By the way, do you know if the Santa Clara Study uses “confirmed” deaths or “total” deaths? They do not specify it, but cite this website as a source (which does not specify it either, unfortunately): https://www.sccgov.org/sites/covid19/Pages/dashboard.aspx#cases

Thank you so much,
Patrick

**Comment by InALunch** [comment]
Is there an update on this? The choice of different metrics to use is leading to a large discrepancy, for example [Worldometers](https://www.worldometers.info/coronavirus/country/us/) is reporting 18,929 deaths for New York State(similar numbers on JHU map, but harder to disentangle), while COVID Tracker is reporting 14,347 deaths [here](https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#).

In particular, I'm interested in forecasting whether the numbers of deaths reported will change by April 26, since this is germane to a number of forecasts I'd like to do.
