### ISSUE TITLE
Covid19Tracking Deaths differ from Johns Hopkins Coronavirus Site

### ISSUE THREAD

**Issue by BrianSublett** [COVID19Tracking/issues#222]
Why do the number of U.S. deaths on your Covid19 Tracking site differ so much from the Johns Hopkins Coronavirus site?  For today (4-18-20) your site reports 34,139 U.S. deaths, while the Johns Hopkins site reports 38,910 U.S. deaths.  I've been watching them both and they seem to have matched fairly well until about 2 days ago.
Johns Hopkins Coronavirus site:
https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

**Comment by muamichali** [comment]
Hi Brian,

The reason for the discrepancy is that NYC on 4/14 added more than 3700 presumed deaths retroactively to its deaths count. 
https://www.reuters.com/article/us-health-coronavirus-usa-idUSKCN21W20G

We have not yet added these presumed historical deaths into our reports.

**Comment by sincav87** [comment]
Thank you for "qualifying" this data and keeping it segregated for now.  What will the standard be to include it, or not?  You might also question the Positive Case numbers for NYC as well since there is mounting evidence that several NY hospitals are indiscriminately using the unique CDC-issued "Covid-19" code.  It's difficult to find these number reliable when U.S. Medicare and CARES Act funding is tied to Covid-19 patient load.  It could be 1-2 years before any of these numbers are audited.  You might qualify that in your reporting as well.  Kevin Sincavage, Emerson NJ

**Comment by muamichali** [comment]
Thank you, Kevin. 

NYC has been publishing a daily report of confirmed and suspected COVID deaths in Github. [You can see it here. ](https://github.com/nychealth/coronavirus-data/blob/master/probable-confirmed-dod.csv)

In recent days, states are starting to report confirmed as well as probable cases and also deaths. We are watching that development so we can continue to aggregate the most accurate and transparent information.
