### ISSUE TITLE
Washington State Testing Data Issues

### ISSUE THREAD

**Issue by jbkahan** [COVID19Tracking/issues#233]
Please have someone look at the Washington state testing data.   The data you have is incorrect in both totals and most importantly the history of the data.  you can go to https://www.doh.wa.gov/Emergencies/Coronavirus

for the latest data.  and/or connect please directly with me offline. johnka@microsoft.com chief data analytics officer, Microsoft / Global AI for Health lead

**Comment by jstover79** [comment]
I am also seeing problems in WA data.

date | state| pos tests | neg tests
20200414 | WA | 10,538 | 83,391
20200413 | WA | 10,411 | 83,391
20200412 | WA | 10,224 | 83,391
20200411 | WA | 10,224 | 83,391
20200410 | WA | 10,224 | 83,391
20200409 | WA | 9,769 | 83,391
20200408 | WA | 9,506 | 83,391
20200407 | WA | 9,043 | 83,391
20200406 | WA | 8,679 | 83,391

Here's the most recent official WA state data from their website (transcribe form their graph since their downloadable file censors counties with 5 or fewer cases:

4/14/2020 | 10737
4/13/2020 | 10535
4/12/2020 | 10347
4/11/2020 | 10114
4/10/2020 | 9895
4/9/2020 | 9447
4/8/2020 | 9167
4/7/2020 | 8812
4/6/2020 | 8476

The totals gathered from adding up usafacts.org county level data matches the official WA data more closely.

**Comment by careeningspace** [comment]
Hello,

I apologize for the delay in cleaning up the WA numbers. They update them regularly so it is a bit of a chore to keep them current. I have updated the numbers to match as-of 4/25.

From WA:
![Screen Shot 2020-04-27 at 8 47 39 AM](https://user-images.githubusercontent.com/43073915/80379608-56a94200-886c-11ea-9366-f505d3e0f89e.png)
![Screen Shot 2020-04-27 at 8 44 17 AM](https://user-images.githubusercontent.com/43073915/80379609-56a94200-886c-11ea-8350-f555f747c133.png)
![Screen Shot 2020-04-27 at 8 29 01 AM](https://user-images.githubusercontent.com/43073915/80379612-5741d880-886c-11ea-84c3-032e04ab947a.png)
![Screen Shot 2020-04-27 at 8 25 34 AM](https://user-images.githubusercontent.com/43073915/80379613-5741d880-886c-11ea-8790-63cabc78442b.png)
![Screen Shot 2020-04-27 at 8 17 59 AM](https://user-images.githubusercontent.com/43073915/80379616-5741d880-886c-11ea-91e4-6da33c78307f.png)
![Screen Shot 2020-04-27 at 8 15 26 AM](https://user-images.githubusercontent.com/43073915/80379618-57da6f00-886c-11ea-8c13-2cedd5ec39d8.png)
![Screen Shot 2020-04-27 at 8 14 25 AM](https://user-images.githubusercontent.com/43073915/80379620-57da6f00-886c-11ea-8bed-f35f9ac1fe27.png)
![Screen Shot 2020-04-27 at 8 13 16 AM](https://user-images.githubusercontent.com/43073915/80379621-57da6f00-886c-11ea-85f7-7a48dfacb56b.png)
![Screen Shot 2020-04-27 at 8 12 09 AM](https://user-images.githubusercontent.com/43073915/80379623-58730580-886c-11ea-839f-fc1815a5a795.png)
![Screen Shot 2020-04-27 at 8 09 37 AM](https://user-images.githubusercontent.com/43073915/80379625-58730580-886c-11ea-924a-666f797b4269.png)
![Screen Shot 2020-04-27 at 8 08 51 AM](https://user-images.githubusercontent.com/43073915/80379626-58730580-886c-11ea-9240-1e86bbb39442.png)
![Screen Shot 2020-04-27 at 8 07 48 AM](https://user-images.githubusercontent.com/43073915/80379629-590b9c00-886c-11ea-9333-9f52127c85e1.png)
![Screen Shot 2020-04-27 at 8 06 36 AM](https://user-images.githubusercontent.com/43073915/80379630-590b9c00-886c-11ea-90df-0f4b6f7cd5c2.png)
![Screen Shot 2020-04-27 at 8 04 09 AM](https://user-images.githubusercontent.com/43073915/80379632-590b9c00-886c-11ea-8055-3d56e97ed389.png)

Updated CTP Data:
![Screen Shot 2020-04-27 at 9 46 28 AM](https://user-images.githubusercontent.com/43073915/80379662-62950400-886c-11ea-86a0-6337e99b2bc8.png)

**Comment by jbkahan** [comment]
terrific


John Kahan
425-442-2325
https://www.linkedin.com/in/johnkahan/
www.GiveToStopSIDS.org<http://www.GiveToStopSIDS.org>
