### ISSUE TITLE
Simple problem with Georgia

### ISSUE THREAD

**Issue by carolyn4** [COVID19Tracking/issues#236]
The Georgia numbers update twice a day:  First noon, or a little before. Second 7:00pm or a little before. However, your afternoon data grab happens at 6:05pm and thus only repeats the previous update. Maybe it's a Daylight Savings issue, because I think it used to go at 7:05 which was perfect. So if you could simply adjust it to 7 or so we'd have better evening data and historical data going forward.  Thanks!

**Comment by goldfarb** [comment]
Thank you for the suggestion, @carolyn4 

Because we are updating all of the states and territories at once, we have tried to find times which capture updates in a comprehensive way. I think that whatever time we choose, we will just miss the schedule for a state or two.

We do three data captures a day, so that there isn't too long between the state update and our capture, and we will continue to try to find the best times to do so.
