### ISSUE TITLE
Washington COVID

### ISSUE THREAD

**Issue by mlgnight** [COVID19Tracking/issues#238]
https://covidtracking.com/data/state/washington#historical positives dropped from 4/19 to 4/20

**Comment by muamichali** [comment]
Thanks for reporting this issue @mlgnight!

If you scroll down to the top of the page, we publish notes that explain these kinds of issues if we know about them. In this case, it was a data revision by the state `(4/19/20) are lower than yesterday. Data cleaning that occurred late on 4/18 removed 190 confirmed cases that were discovered to be out of state residents.`

**Comment by jstover79** [comment]
I was just checking WA state data and comparing to yours. I'm sure they won't perfectly line up since the WA state data is probably cleaned/edited from time to time for various reasons (adding/subtracting cases due to data entry errors, or like this one where some individuals were from out of state). I just wanted to make sure that this is to be expected (e.g. once your data is finalized for a particular date, it isn't updated. It might be nice to have a separate tracking database that does automatically update as states update there data. I also checked against the usafact.org dataset, and found similar discrepancies form the official WA state count. Either way, thank you so much for your work!

**Comment by muamichali** [comment]
@jstover79 You are very welcome. If you find data that we need to update and report it here as new issue with state sources, we will do our best to correct historical data.
