### ISSUE TITLE
SC: Data not updating

### ISSUE THREAD

**Issue by eric-czech** [COVID19Tracking/issues#24]
I noticed that the SC counts didn't update last night (https://covidtracking.com/data/state/south-carolina/):

![Screen Shot 2020-03-20 at 8 35 05 AM](https://user-images.githubusercontent.com/6130352/77164033-c7975600-6a85-11ea-8f1b-c4ebd0614cf0.png)

Is there some way to verify that this was due to the underlying source (currently https://scdhec.gov/monitoring-testing-covid-19) not updating rather than some collection bug?  

Similarly, is it possible to get a sense of how often underlying source pages are changing?  I'm not sure if the SC monitoring page is being updated multiple times daily or not, and I thought something collected by the current crawlers might give me that sense.

**Comment by hammer** [comment]
@eric-czech the current count for SC is 81 so looks like this was due to either SC reporting late or us not checking it near enough to 4 pm. It's an acknowledged caveat with our data: https://covidtracking.com/newsroom-expert-faq. We do keep a log of each time a state has been checked, so we could conceivably generate a report on which states update multiple times per day, but that's not something we do currently nor do we plan to do it soon.
