### ISSUE TITLE
RI 4/19 Data inconsistency

### ISSUE THREAD

**Issue by iservin** [COVID19Tracking/issues#241]
It appears today RI DOH retroactively changed their positive test numbers for Sunday 4/19.

They had originally published 4,706 positive tests as a total as of Sunday. Today the historical numbers for that date now shows 4,751 positive tests. 

This is why the calculated new positive case number 384 is out of sync with the DOH's published number of 339.

**Comment by karaschechtman** [comment]
RI DOH's day by day historical data: https://docs.google.com/spreadsheets/d/1n-zMS9Al94CPj_Tc3K7Adin-tN9x1RSjjx2UzJ4SV7Q/edit#gid=1998687529

There are noticeable revisions upwards between our data/what RI was reporting in the past vs. what RI reports now in the spreadsheet for 4/18-4/23. Updating pos, cur hosp, cum hosp, and deaths for those days (negs were also reported but were the same as our data).
Our data before:
![RI data 4:18-4:23 before2](https://user-images.githubusercontent.com/15933271/81194601-d761ef80-8f8a-11ea-9c6c-bef0aec226a2.png)
Our data after:
![RI data 4:18-4:23 after](https://user-images.githubusercontent.com/15933271/81194618-dd57d080-8f8a-11ea-9557-f1f54c5a5efc.png)
RI state data as of 5/6/2020:
![RI State data](https://user-images.githubusercontent.com/15933271/81195116-6bcc5200-8f8b-11ea-8f7d-f97043e51031.png)

In addition, we noticed there was a one-day lag for positives for all the RI data, so changed the timestamps on the last updated field to 00:00 the day of the check for each day of data.
Before:
![before last updated RI 1](https://user-images.githubusercontent.com/15933271/81195031-50614700-8f8b-11ea-9b46-2efc839fc4a6.png)
![before last updated RI 2](https://user-images.githubusercontent.com/15933271/81195033-50614700-8f8b-11ea-8987-d3c2d1d9f4c6.png)
After:
![last update after](https://user-images.githubusercontent.com/15933271/81195842-59064d00-8f8c-11ea-8b64-91a9409a38a4.png)
![last update after2](https://user-images.githubusercontent.com/15933271/81195846-59064d00-8f8c-11ea-8a1f-254a2c368baa.png)

Because there may be other discrepancies hiding in the RI DOH spreadsheet, I will write a script to compare the two csvs to catch any further potential changes
