### ISSUE TITLE
U.S death totals, NY especially, are significantly lower than those reported on other site.

### ISSUE THREAD

**Issue by cdflower** [COVID19Tracking/issues#268]
Seems to be tied to revised death counts, which may not be picked up by your sources?

E.g. NY increased their death count significantly (3700?) on 4/16, which is not picked up in your data. 

Reference sites: 91-DIVOC, Worldometer, Johns Hopkins

**Comment by MadDr33** [comment]
Still potentially a big problem with the under reporting deaths in NY state.   On 4/26 you reported 49153 whereas Worldometer reported 55413 (+6260!).  Also a smaller discrepancy for PA, 1550 vs.1823 for Worldometer.   This is affecting the US total which is over 55,000 at Worldometer and only 49153 on your table.

**Comment by OrionEridanus** [comment]
Tweet is vague.  It implies(to me)  that the discrepancy is due to the difference between deaths attributed to COVID but not confirmed by test...but this requires an assumption.

There is a HUGE difference between worldometers total fatalities in the U.S. and the total here (as of this moment, this site lists a net 61,688 deaths.  Worldometers lists 68,609.  This is nearly a 10%(!) difference.

What is the cause of the difference, and please post this in a text box in your google docs worksheets and on the web pages.
