### ISSUE TITLE
Hawaii positive increase on 4/22 is a negative number

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#272]
At present, the data returned by:

`https://covidtracking.com/api/v1/states/daily.json`

Shows the following value for `state = HI` on `date = 20200422`:

`"positiveIncrease":-2`

I have not checked for the presence of any other negative values, but this is the only one I've come across so far.

**Comment by hrushka** [comment]
> I got curious and wrote a tool to find errors like this:
> https://www.covidcharts.com/data_check.html
> 
> Entirely client-side JS, so feel free to re-use any of the code.

This is fantastic. Great work @loglow. I've been visually grepping through the same, but using the CSV datasource for https://c19.dev.

**Comment by the-daniel-lin** [comment]
"There's a potential corruption of your Confirmed Positives historical data for several states. The data as reported should be cumulative amounts i.e. either increasing or constant - but in several places there have been new spikes added to past data and occasional dips, both producing negative Daily Positives after day-to-day subtraction. This is a recent development. I compared the current report with one ending on May 31 - and the discrepancies are (format: State, date new/old values or a multiday up-and-down sequence): ... 5) HI, 4/21-22, 584, 582...." Instead of 584, 582, the values should be 584, 586.

Screenshot from state site on 4/21:
![image](https://user-images.githubusercontent.com/67408226/87961620-d6f5d280-ca6a-11ea-9b5f-880a9fc2f2db.png)

Screenshot from state site on 4/22:
![image](https://user-images.githubusercontent.com/67408226/87961695-f3920a80-ca6a-11ea-8abb-3762d25b8929.png)

***Our data for HI uses numbers "as of" the previous day according to the site

**Comment by MattHilliard** [comment]
Independently checked the screenshots. The 6pm HI screenshot for 4/22 says 592 cases, but the surrounding numbers indicate the 12:00 screenshot matches what data entry was doing so I'm using the 12:00 number, 586.

Before:
![image](https://user-images.githubusercontent.com/404503/87993211-f830e000-cab7-11ea-8ad4-aef0fd9f2e07.png)

After:
![image](https://user-images.githubusercontent.com/404503/87993231-01ba4800-cab8-11ea-8e5b-01bb6b6b4515.png)

Regarding WA on 4/20, there's no longer a decline in cases on that day. I think that was probably fixed as part of a previous backfill of Washington historical data.
