### ISSUE TITLE
Georgia Daily Positive Test Count Wrong

### ISSUE THREAD

**Issue by kbalzli** [COVID19Tracking/issues#280]
The last screen shot that is usually the 6 pm hour is just a duplicate of the noon screenshot.  The 6 pm hour screen shot you are not showing until the following day at the 12 am hour. This is causing you to show a lower increase of positive test cases daily.  Can you please correct it ?

**Comment by goldfarb** [comment]
Thank you writing, @kbalzli 

Different states update the public presentation of their data at different times throughout the day. Some are very regular in when they make updates, some update only when there is specific news, some have a daily report. Additionally, the reported numbers are often compiled from testing done the previous day. The schedule for our screen captures is standardized for all of the pages, and while not instantaneous, we will capture the cumulative updates over the course of a day.

The screenshots we take are so that we can go back and double check historical data. The reported values which we include in the available data are collected three times a day, because of the varied reporting schedule from states, and are based on the state sites at the time, not the screen captures.
