### ISSUE TITLE
[States Daily CSV] AR deathIncrease is negative for 2020-04-22

### ISSUE THREAD

**Issue by acobolew** [COVID19Tracking/issues#290]
AR deathIncrease is negative for 2020-04-07:
> library(data.table)
> covidtracking.dt <- fread('https://covidtracking.com/api/v1/states/daily.csv')
> covidtracking.dt[, date := as.Date(as.character(date), '%Y%m%d')]
> covidtracking.dt[order(date, decreasing=FALSE)][ , .(date, state, death, deathIncrease) ][deathIncrease < 0]
         date state death deathIncrease
1: 2020-04-05    VA    51            -1
2: 2020-04-07    DC    22            -2
**_3: 2020-04-22    AR    42            -1_**
4: 2020-04-23    PA  1421          -201
5: 2020-04-24    KS   111            -1
6: 2020-04-24    TN   168            -2

**Comment by jaclyde** [comment]
1: 2020-04-05 VA 51 -1: We reported what the state reported that day (and the previous one). Minor revisions to totals are to be expected. (https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1586111217490700)

2: 2020-04-07 DC 22 -2: Same as above. (https://covidtracking.com/screenshots/DC/DC-20200407-000410.png)

3: 2020-04-22 AR 42 -1: Total deaths decreased by one because the person was determined to not be a resident of Arkansas (https://youtu.be/w8GFXc1uI10?t=762). 

4: 2020-04-23 PA 1421 -201: PA removed Probable cases from their Deaths (confirmed and probable) total, causing a decrease of 201. (https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1587666293030300)

5: 2020-04-24 KS 111 -1: KS Deaths (confirmed and probable) decreased by one due to the removal of a death determined to not have been from Covid-19. (https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1587753146177000)

6: 2020-04-24 TN 168 -2:  We reported what the state reported that day (and the previous one). Minor revisions to totals are to be expected. (https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1587758686214100)
