### ISSUE TITLE
Error in # of recovered patients in Michigan

### ISSUE THREAD

**Issue by ppasquar** [COVID19Tracking/issues#298]
Hi,
the number of recovered patients in a state should be cumulative; however, in Michigan, that number first increases, then declines, and finally it increases again, starting with April 3; see below:

56
56
56
56
56
56
56
56
595
433
447
452
452
617
629
3237
3237
3237
3237
3237
3237
3237

I hope this helps,

Paolo

**Comment by karaschechtman** [comment]
Hi @ppasquar,
Thanks for pointing this out. 
On 4/11, when the number decreases from 595 to 433, we started using a new official figure for recoveries rather than ED discharges:
<img width="228" alt="Screen Shot 2020-05-20 at 10 10 11 AM" src="https://user-images.githubusercontent.com/15933271/82456701-938ae200-9a82-11ea-8d82-424f85d286a7.png">

**Comment by ppasquar** [comment]
Thank you Kara!

Paolo

Paolo Pasquariello
Professor of Finance
Stephen M. Ross School of Business
University of Michigan
701 Tappan Street, room R4434
Ann Arbor, MI 48109-1234
email: ppasquar@umich.edu
phone: 734-764-9286

webpage: http://webuser.bus.umich.edu/ppasquar/
SSRN research page:
https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=250093
<http://ssrn.com/author=250093>
Google Scholar page:
https://scholar.google.com/citations?user=ByzWEGMAAAAJ&hl=en
LinkedIn profile: https://www.linkedin.com/in/paolo-pasquariello-376247/
