### ISSUE TITLE
Minnesota test count way off for 4/25

### ISSUE THREAD

**Issue by Minibadger** [COVID19Tracking/issues#301]
Minnesota's test count as posted on Saturday 4/25 per the Department of Health website was 2,810. Your data is off by 2x at 5612 or something similar, yet it cites the Department of Health website as the source...

**Comment by muamichali** [comment]
Thanks for writing @Minibadger 

There was a data entry error in entering Minnesota's negative numbers yesterday that caused this to happen. We are going to correct it. 

<img width="220" alt="Screen Shot 2020-04-26 at 4 22 52 PM" src="https://user-images.githubusercontent.com/1749380/80318835-d4bd0880-87da-11ea-9dd8-4b8d57293a15.png">

<img width="215" alt="Screen Shot 2020-04-26 at 4 26 03 PM" src="https://user-images.githubusercontent.com/1749380/80318836-da1a5300-87da-11ea-9f81-8e44cffbb052.png">

**Comment by dan4est** [comment]
'totalTestResults' on 4/24 is 56336, should be 53787
'totalTestResults' on 4/25 is 59699, should be 56597

Leads to corresponding errors in 'negative' for 4/24 and 4/25, and 'negativeIncrease' and 'totalTestResultsIncrease' for 4/24, 4/25, and 4/26.

**Comment by muamichali** [comment]
@dan4est Yes. You are correct. The original data patch caused an issue because it was on the wrong cell. Here is the correct one. It should be reflected on the website this afternoon.

<img width="210" alt="Screen Shot 2020-04-27 at 1 02 51 PM" src="https://user-images.githubusercontent.com/1749380/80399726-a9dcbe00-8887-11ea-8ec9-f70fe7cd6bc9.png">
