### ISSUE TITLE
Georgia - Test Count (May 3)

### ISSUE THREAD

**Issue by dcorbin** [COVID19Tracking/issues#355]
The historical data for Georia on May 3 shows 296 new tests.  But the screen shot (all 4) show 174,800, the same number as the last screenshot on May 2.

**Comment by karaschechtman** [comment]
Hi @dcorbin,
Thank you for bringing this to our attention. This problem is being caused by a thorny issue with negative tests. States tend to have different reporting standards for negative tests, with some reporting negatives, and some not. For states that do not report negatives, the best estimate we can get of that data point is subtracting the number of positives from the total. GA is one of those states.

However, in GA, positive test figures tend to lag total test figures. This lag means that sometimes, when we infer the count of negatives, it appears as if the number of negative tests has decreased. Since one of our principles is to never decrease negatives over the historical time series, in these cases we carry over our calculated negative figure from the previous day. That is what happened here: we carried over a higher negative figure because the totals did not update, so when we add positives+negatives (the figure we use to calculate "new tests"), it appears to grow even if it stayed constant on the website.

We are considering a number of measures to address this problem, including deprecating negatives or changing total tests to draw from "Totals" rather than positives+negatives (although this may be confusing since then pos+neg will sometimes be greater than total).

I hope this explanation is helpful. Thank you for bringing it to our attention.
