### ISSUE TITLE
Virginia cumulative number of tests decreases on 02 May

### ISSUE THREAD

**Issue by rplzzz** [COVID19Tracking/issues#357]
I think this is probably related to #351.  As a result of this change in the counting, the cumulative number of tests decreases on the day of the change-over, which causes a lot of headaches for many uses of the data.  Is there any possibility of including both ways of counting, so that users can choose whichever one makes sense for their purposes?

**Comment by quangnguyen1995** [comment]
Thank you very much @rplzzz for your feedback! Unfortunately, as states change their reporting standards, there are many decisions we have to make in order to keep our data definitions consistent. We have been keeping track of both numbers since they were reported, and is working internally to best represent those numbers, where possible.
