### ISSUE TITLE
WA data out of date and timestamp looks wrong

### ISSUE THREAD

**Issue by easp** [COVID19Tracking/issues#383]
Page in question: https://covidtracking.com/data/state/washington

As of 10:15AM PDT:

"Last updated from our data: 1:12 pm EDT"

Data hasn't been updated to reflect last update on state website made 4:30pm PDT 5/6/2020 (which shows data as of Last updated: Tuesday May 5 2020 11:59 pm PDT).

Page lists last updated as "Last updated: Mon May 4 2020 11:59 pm EDT." Is that accurate, or should it reflect the state's cutoff time, which is 11:59 *PDT*?

Last screenshot, dated Wed May 6 2020 at 9:24PM (EDT) is blank (file exists, but renders as white).

Prior screenshots show the web page, but they don't show any data due to the sections being collapsed. Probably a result of how "screenshot" is taken. Some tools that allow capture of entire rendered webpage allow interaction with page before capturing final page state.

Screenshots are not of the page [linked under best current data source](https://www.doh.wa.gov/Emergencies/NovelCoronavirusOutbreak2020COVID19/DataDashboard). They are of [this page](https://www.doh.wa.gov/Emergencies/Coronavirus)

**Comment by muamichali** [comment]
Thanks for contacting us @easp 

Let me try to respond to all the points you raised 

1. We publish the data daily around 4.30pm EST, so when a state adds data after our publishing cut off time, we capture it the following day

2. > Page lists last updated as "Last updated: Mon May 4 2020 11:59 pm EDT." Is that accurate, or should it reflect the state's cutoff time, which is 11:59 PDT?
We are going to look at this. It might be a timezone reporting issue 

3. Screenshots
We updated the screenshots logic this morning to point to the dashboard since the main page recently stopped showing the data. We are looking into why the screenshot capturing tool got a blank page.

**Comment by muamichali** [comment]
The timezone issue reported above as #2 should be fixed with https://github.com/COVID19Tracking/website/pull/848
