### ISSUE TITLE
Georgia table of total cases - data doesn’t match.

### ISSUE THREAD

**Issue by lkhemani** [COVID19Tracking/issues#402]
After the glitch on April 27/28, your Georgia daily totals under-represent the final screen print from ~6pm each day. 

For examples, check  your last daily screen shot vs. your numbers in the table on this page for every day since April 29:
https://covidtracking.com/data/state/georgia

**Comment by erfgottlieb** [comment]
Thanks @lkhemani 
Sometimes the state screenshots are taken after our reporting schedule. Please see issue #280 for a detailed explanation.

**Comment by lkhemani** [comment]
@erfgottlieb, I looked at issue #280, but what I am reporting is actually the opposite.  Your table indicates that the final total was taken at 6:08pm, but the number listed is actually **lower** than the number on the screen shot from 5:25 pm.  This means the data was underreported for that day.  I see that was corrected on the 13th by stopping daily totals for GA at ~1:00pm so that the screen shots now match, but it is still a bit misleading to say that the last total was collected at 6pm when it is 5 hours off. Why not just say that it was collected at 1pm for accuracy? Another data integrity issue would be that the data Indicates 100 more cases were reported from the 12th to 13th than actually were reported. I don’t know how much you guys care about daily accuracy, but if that matters to you, you may want to just update the tables.  The screen share was actually more up to date than your table, and it was taken earlier. I appreciate that you are all volunteers and I don’t want to look a gift horse in the mouth, I just am trying to help maintain data integrity by pointing out potential inaccuracies.  Thanks Very Much for your time...this is an invaluable service and I appreciate all that you guys are doing.

**Comment by erfgottlieb** [comment]
Hi @lkhemani thanks so much for your comments. We collect data manually from the states' data dashboards or department of health websites. We take automated screenshots of those websites several times a day. The screenshot times are listed and linked here: https://covidtracking.com/data/state/georgia#historical. For many states, the screenshot timing does not occur at the same time as our manual data entry. It seems that the discrepancy that you are seeing on April 27/28 is due to this.
This might be the same explanation for your question about the number of cases reported from the 12th to 13th. Can you let us know which month this was in?

**Comment by lkhemani** [comment]
Oops! It was May 12-13.  Thanks.
