### ISSUE TITLE
New hospitalizations for today (5/10) is currently being reported as -2432

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#403]
Sunday, May 10 shows a very large negative number (-2432) for new hospitalizations.

**Comment by dpthurst** [comment]
WA cumulative hospitalizations yesterday (5/9) were entered as 3,450, and should have been reported as no data. That may account for part of this.

**Comment by erfgottlieb** [comment]
Thanks @loglow . Can you send us a link for the New Hospitalizations numbers that you are seeing for May 10?

**Comment by loglow** [comment]
`"hospitalizedIncrease":-2432`

https://covidtracking.com/api/v1/us/daily.json

**Comment by loglow** [comment]
![68AD8BA6-F0DF-4887-AD6C-9AB2870A668F](https://user-images.githubusercontent.com/3103472/81627171-98d59600-93cb-11ea-8d2a-b1e549149aed.jpeg)

**Comment by loglow** [comment]
This is not looking so great...

Another large negative number (-3120) is being reported for hospitalizedIncrease on 5/12.

I'm not sure why this is happening, but it seems like this number should never be negative.

If the problem is in previous days reporting, then shouldn't the values be retroactively corrected?

<img width="659" alt="Screen Shot 2020-05-13 at 6 20 32 AM" src="https://user-images.githubusercontent.com/3103472/81801407-610d4200-94e2-11ea-9ffa-723466b51cfd.png">

**Comment by muamichali** [comment]
I corrected the issue for the WA hospitalizations historic data as per @dpthurst's comment. 
I am looking for the root cause of the 5/12 issue. 

**BEFORE**
![Screenshot_2020-05-14 Coronavirus numbers by state (CovidTracking, DEV COPY)(3)](https://user-images.githubusercontent.com/1749380/81954243-9f842900-95d6-11ea-8f66-fe01d6cfc0ee.png)

AFTER 
![Screenshot_2020-05-14 Coronavirus numbers by state (CovidTracking, DEV COPY)(4)](https://user-images.githubusercontent.com/1749380/81954421-d4907b80-95d6-11ea-8866-e08d92792465.png)
