### ISSUE TITLE
NJ 5/11 Test Increase

### ISSUE THREAD

**Issue by Prindle19** [COVID19Tracking/issues#409]
Showing a single day increase in tests for NJ of  113486? That's a huge jump, is this accurate?

**Comment by realfuture** [comment]
That’s how they reported it. We’re trying to track down precisely why they had this big backlog.

We believe it is similar to what happened in California a couple weeks ago. They changed both what they are reporting (switching to test completed instead of people tested) — and put out a huge number of tests.

We’ll let you know if we can get more clarity from the state.

A

**Comment by Prindle19** [comment]
Interesting, where does this data come from specifically? I don't see it on the https://covid19.nj.gov/#live-updates dashboard 

I filed an OPRA request back in April to get test data by the actual day of the test (haven't heard back of course)

**Comment by muamichali** [comment]
@Prindle19 it was on their dashboard yesterday afternoon as 425,933. Here is a screenshot we captured. https://covidtracking.com/screenshots/NJ/NJ-20200511-184534.png 
It is currently up to 433,060 
I think that it showed up as pending on their dashboard when you asked.

**Comment by Prindle19** [comment]
Got it, yeah found that today, thank you! Also noted that now there's a note saying that this could include re-tests...wondering if that has always been the case, and whether the "confirmed cases" could represent multiple positive tests of the same patient...

**Comment by muamichali** [comment]
Hi @Prindle19 

I am closing this issue. We are watching closely all aspects related to what exactly is being reported from each state.
