### ISSUE TITLE
AK, DC, ID, MI, NY, NV have non-cumulative results

### ISSUE THREAD

**Issue by nickblink** [COVID19Tracking/issues#41]
For DC and NV, there is a day when positive tests decrease from the previous day. For the other four states, there are days when negative tests decrease.

Thanks for putting this together!

**Comment by AceChenX** [comment]
For NY, total tests decrease between Mar 7-8 and 10-11.

**Comment by mymil** [comment]
Uploading a spreadsheet of **all** decreases (more than documented previously), current as of today: 
[covidtracking_problemdates.xlsx](https://github.com/COVID19Tracking/issues/files/4382958/covidtracking_problemdates.xlsx)

States affected: AK, AL, AZ, CO, DC, DE, FL, HI, IA, KS, MA, MD, MI, NJ, NM, NV, NY, OH, OK, PR, RI, SC, WI

This is my R code to calculate new cases and pull records that decreased from the prior day (any variable) AND the prior day's row for comparison:
```
library(tidyverse)
covidtracking %>% 
    arrange(state, date) %>% 
    group_by(state) %>% 
    mutate_at(vars(c("positive", "death", "total")), 
              list(new = ~ coalesce(. - lag(.), .))) %>%
    filter_at(vars(ends_with("new")), any_vars(. < 0 | lead(.) < 0)) %>% 
    ungroup()
```

**Comment by breyed** [comment]
I wonder if the problem is an error in the data source in which corrections for prior day results are included as adjustments on the day the error was discovered. This is common in the banking world because of the value of keeping past transactions immutable. It's poor practice for scientific data, however, because the test counts on a given day matter.

If the problem is deferred adjustment, the idea solution is to inform the data sources and ask for better quality data. Short of that, an corrective approach is to reverse the error to the best extent that the data allows: Where a daily result is negative, set that day to zero, and decrease the count of the previous day by the corresponding amount.

Such a correction would not be perfect since (a) you don't know for sure whether the error was from the previous day versus earlier and (b) it doesn't correct any of the cases where adjustments didn't cause negative result. Still, it leads to better data quality than making no correction and avoids the confusion of negative daily counts.

**Comment by careeningspace** [comment]
Hello, and thank you for helping us clean our data. Please see the following:

**New York:**
- [ ] 3/7 to 3/8 the total changed due to pending tests no longer being reported.
- [ ] 3/10 to 3/11 should be correct
![Screen Shot 2020-03-25 at 10 24 00 AM](https://user-images.githubusercontent.com/43073915/77547108-280e0500-6e83-11ea-8d52-fc3378aa959f.png)

**Oklahoma**
- [ ] 3/20 to 3/21 the variance in totals is tied to the unreliable Pending category. It may be that the data point was phased out and our data was affected by this transition;
![Uploading Screen Shot 2020-03-25 at 10.29.12 AM.png…]()

**Ohio**
- [ ] 3/16 to 3/17 variation in data is due to Pending data no longer being published.
![Screen Shot 2020-03-25 at 10 49 57 AM](https://user-images.githubusercontent.com/43073915/77549590-6b1da780-6e86-11ea-9e54-ee33802827fd.png)

**New Jersey**
- [ ] 3/16 is infact incorrect:
![Screen Shot 2020-03-26 at 8 57 10 AM](https://user-images.githubusercontent.com/43073915/77649235-e1321500-6f3f-11ea-87a8-749714362f47.png)
- [ ] corrected
![Screen Shot 2020-03-26 at 8 57 23 AM](https://user-images.githubusercontent.com/43073915/77649263-f313b800-6f3f-11ea-9e68-24b605c42926.png)

**Hawaii**
- [ ] Pending for 3/19 decrease per the state
![Screen Shot 2020-03-26 at 8 59 28 AM](https://user-images.githubusercontent.com/43073915/77649432-3bcb7100-6f40-11ea-98cc-35068a179919.png)

**Michigan** stopped reporting pending data as of 3/17

**Kansas** stopped reporting pending data as of 3/11 
![Screen Shot 2020-03-26 at 9 08 59 AM](https://user-images.githubusercontent.com/43073915/77650192-7aadf680-6f41-11ea-9b0c-bc01d40e3c44.png)

**Iowa** stopped reporting pending data as of 3/14
**Deleware** stopped reporting pending data as of 3/17
**DC** has fluctuating pending data
![Screen Shot 2020-03-26 at 9 10 51 AM](https://user-images.githubusercontent.com/43073915/77650352-c365af80-6f41-11ea-99a5-fd33d3814a95.png)

**Comment by mymil** [comment]
Thank you for these clarifications, @careeningspace, and for working on providing these data so accessibly! In terms of cleaning up these records for use:

1. Has the NJ correction been applied to the live data?
2. Given the inconsistencies with pending data, do you foresee any problems with subtracting pending cases from the totals?

**Comment by careeningspace** [comment]
The NJ correction should be in the live feed. Going forward, our API will no longer be focusing on including Pending in our "Total". You can find more detail on our [API Page](https://covidtracking.com/api/)
- [ ] totalTestResults - Calculated value (positive + negative) of total test results.
- [ ] total - DEPRECATED Will be removed in the future. (positive + negative + pending). Pending has been an unstable value and should not count in any totals.

**Comment by mymil** [comment]
Great, thanks. That fixes problems in many states and leaves only AK, DC, HI, ID, KY, MI, NV, and SC with negative "increases":
[covidtracking_problemdates.xlsx](https://github.com/COVID19Tracking/issues/files/4393534/covidtracking_problemdates.xlsx)

`covidtracking %>% arrange(state, date) %>% group_by(state) %>%  filter_at(vars(ends_with("Increase")), any_vars(. < 0 | lead(.) < 0)) %>% ungroup()`

**Comment by careeningspace** [comment]
-[ ] Alaska has a period of data flux that needs more research 3/17 - 3/19: 
Data Log:
![Screen Shot 2020-04-02 at 10 28 34 AM](https://user-images.githubusercontent.com/43073915/78261233-fa513d80-74cc-11ea-8fd6-501820e8cb3c.png)

Daily Report:
![Screen Shot 2020-04-02 at 10 31 38 AM](https://user-images.githubusercontent.com/43073915/78261437-3b495200-74cd-11ea-8d4b-2b75b34e8146.png)

State Data from 3/17 14:09 ET:
![Screen Shot 2020-04-02 at 12 15 47 PM](https://user-images.githubusercontent.com/43073915/78272770-f37df700-74db-11ea-9642-413955f3aefa.png)

State Data from 3/17 18:00 ET:
![Screen Shot 2020-04-02 at 11 57 45 AM](https://user-images.githubusercontent.com/43073915/78270937-879a8f00-74d9-11ea-8621-d32f1333b8e6.png)

State Data from 3/18:
![Screen Shot 2020-04-02 at 11 56 53 AM](https://user-images.githubusercontent.com/43073915/78271051-ae58c580-74d9-11ea-8031-f4618c4662f2.png)

Updated Daily after correction:
![Screen Shot 2020-04-02 at 12 19 02 PM](https://user-images.githubusercontent.com/43073915/78272980-33dd7500-74dc-11ea-993c-114ab2683a64.png)

**Comment by careeningspace** [comment]
District of Columbia 3/10 - 3/11 
- [ ] We do not have screen grabs from this time period
- [ ] It looks like DC changed how they were reporting data. I am going to make both days match

DC Before update:
![Screen Shot 2020-04-02 at 12 25 36 PM](https://user-images.githubusercontent.com/43073915/78273887-6b005600-74dd-11ea-92fc-c1c9ce8824bd.png)

DC after update:
![Screen Shot 2020-04-02 at 12 28 00 PM](https://user-images.githubusercontent.com/43073915/78273915-70f63700-74dd-11ea-8fb6-bdb152ae6af7.png)

**Comment by careeningspace** [comment]
- [ ] ID has an issue with a change in data from 3/18 to 3/19
![Screen Shot 2020-04-02 at 10 40 26 PM](https://user-images.githubusercontent.com/43073915/78318525-f952f700-7532-11ea-8fda-612743140fea.png)

- [ ] Screen cap of State Data from 3/18 14:04:
![Screen Shot 2020-04-02 at 10 44 18 PM](https://user-images.githubusercontent.com/43073915/78318751-9150e080-7533-11ea-9d07-d69c33588458.png)

- [ ] Screencap of State Data from 3/19 14:04:
![Screen Shot 2020-04-02 at 10 41 13 PM](https://user-images.githubusercontent.com/43073915/78318595-2a332c00-7533-11ea-9668-cfe3def8edf1.png)

- [ ] The positives increase, while the total tests reported did not. Our methodology is to leave the negatives unchanged in this case. Fixed data below:
![Screen Shot 2020-04-02 at 10 46 48 PM](https://user-images.githubusercontent.com/43073915/78318873-dc6af380-7533-11ea-9487-5d3c2932acdb.png)
