### ISSUE TITLE
Apply license to our data

### ISSUE THREAD

**Issue by hammer** [COVID19Tracking/issues#42]
Ideally something as permissive as possible from the CC universe https://creativecommons.org/about/program-areas/open-data. I'm not sure if we can though given we are pulling this data from a variety of sources...

**Comment by hammer** [comment]
Just got a request to use our data from an employee of a large company who wanted a contract. It would be nice to get this license up soon!

**Comment by careeningspace** [comment]
Do we need someone to get on this? @hammer

**Comment by tmorrell** [comment]
The CC0 waiver you linked to is a good fit for this data set and is the recommendation from the research data community (https://doi.org/10.5281/zenodo.162241). 

Pulling data from a variety of sources is unlikely to impact your ability to apply a license/waiver. Facts (like x tests were conducted in Michigan) aren't covered by copyright.

The reason to apply a license is that there might be copyright attached to the data when you collect it into your final spreadsheets. Some jurisdictions also have special database rights that could apply.  Copyright is tricky when applied to collections of facts. If you want the data to be widely used, being explicit that copyright doesn't apply allows everyone to not have to worry about legal issues. Users of the data should still cite the project, but this is enforced by community norms instead of copyright.

Note: I'm not a lawyer and this isn't legal advice.
