### ISSUE TITLE
AK - Systemic issues after retroactive State count updates

### ISSUE THREAD

**Issue by scarson** [COVID19Tracking/issues#429]
The CTP AK data has significant divergences from the official AK state data now. The two main issues in the CTP data are off-by-a-day errors and low/no-reporting data where some days' data is missing and aggregated into the next day. The latest official AK state data does not have these gaps. Recommend re-pulling and replacing CTP data with official AK data. Excel sheet with AK official data pulled 5/17: https://drive.google.com/file/d/1OU65DQDNgsglxK38SIL0uu4OaDBSTGqf/view?usp=sharing

Examples:
Missed day:
April 29-30 & May 1
- CTP New Tests
-- 4/29: 2,030
-- 4/30: 0
-- 5/1: 1,206
- AK Official
-- 4/29: 441
-- 4/30: 749
-- 5/1: 1,070

Off-by-one:
May 1-3:
- CTP New Tests
-- 5/1: 1,206
-- 5/2: 1,074
-- 5/3: 179
- AK Official
-- 5/1: 1,073
-- 5/2: 179
-- 5/3: 145

CTP first reported AK death: 4/25
AK official first reported death: 4/16

@thaynedye
@dcmoyer

**Comment by karaschechtman** [comment]
Hi @scarson,
Thanks for reporting this issue (and for reporting similar issues with CA, #431 - #433, which I responded to a few days ago). We've been discussing policy on day lags since then and decided that in order to increase the meaningfulness of the historical data, we will be updating to correct them. I've just checked and AK is on our running list to update with high priority.
