### ISSUE TITLE
WA historical for the last 3-4 days is borked

### ISSUE THREAD

**Issue by stefanba3** [COVID19Tracking/issues#467]
![Annotation 2020-05-22 171828](https://user-images.githubusercontent.com/3440321/82717262-45c3d480-9c50-11ea-97b4-a2d86a3e4825.jpg)

**Comment by theomichel** [comment]
Disclaimer: I'm new here, so my opinions are based on limited context. But I have them in spades! :)

Looking at the screenshots associated with those days, it seems that the data entry was probably correct at the time of entry. (although checkers are not pulling this info from the main dashboard, so the numbers don't quite match the dashboard screenshots)

So as I see it, the main issue here is that washington doesn't push new cases to their site "evenly" every day. They may queue up a batch and then dump it onto the site, and when they do, they assign each new case to the day it was reported to the doctor/hospital. (not the day it was posted to the site)

Since it's been a few days, the sequence of cumulative case counts for 5/17 through 5/22 now looks like this, according to washington:

5/17: 18782
5/18: 18962
5/19: 19139
5/20: 19273
5/21: 19422
5/22: 19731

The short term solution here is to do another data sync, similar to the one done in https://github.com/COVID19Tracking/issues/issues/424 and others. 

The long term solution is some sort of regular backfill process for states that update their historical data over time. (there are several, washington is one example)
