### ISSUE TITLE
New hospitalizations on 6/4 are negative

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#476]
**State or US**: US

**Describe the problem**
`https://covidtracking.com/api/v1/us/daily.json`
`"date":20200604`
`"hospitalizedIncrease":-2828`

**Comment by qpmnguyen** [comment]
Hi @loglow! 

The decrease in new hospitalizations on 06/04 was driven mainly by CT, where a reporting change decreased the number of cumulative hospitalization the state reports. Specifically, the report stated that: "Starting on May 29, CHA changed to only reporting the number of patients with laboratory-confirmed COVID-19; data for previous dates include patients with laboratory-confirmed or suspected COVID-19."

The report can be viewed here: https://portal.ct.gov/-/media/Coronavirus/CTDPHCOVID19summary6042020.pdf

I'm going to close this for now. Please reopen if there are any additional issues!

**Comment by loglow** [comment]
This seems like a situation where the larger previously reported number should continue to be used and carried forward until it is eclipsed by the new reporting criteria.

A negative number in this dataset is confusing and nonsensical.

**Comment by loglow** [comment]
I don't see any way to reopen this issue, perhaps I don't have permission to do so. If I don't hear anything back, I'll probably open a new issue with my above reply.

**Comment by qpmnguyen** [comment]
I can reopen the issue!

This is a bit more complicated than what I can handle right now on Github. Here are some quick personal thoughts:

So far our principle is that we'll always revise down (with good reason) and take a hit so that our future numbers for each state can be more updated and accurate. Sure we can wait for the numbers to climb up by ~4k, but that means possibly weeks where our numbers won't be reflective of what a state reports, and we would lose possibly some important day-to-day changes in the short term. 

However, this is a principle-level change so I'll bring the conversation to the other leads. If you're still on the slack, feel free to join!

Hope this helps!

**Comment by loglow** [comment]
New hospitalizations have been in the range of 1000-2000 per day, so I would think it would take no more than 1-2 days for the reported numbers to catch up.
