### ISSUE TITLE
NH Data doesn't match

### ISSUE THREAD

**Issue by mm3875** [COVID19Tracking/issues#479]
The NH DHHS report on tests per day doesn't seem to match up with  your test data numbers? [
<img width="840" alt="Screen Shot 2020-06-06 at 6 20 29 PM" src="https://user-images.githubusercontent.com/62656472/83955607-798f2480-a822-11ea-93bd-f29931bcaf11.png">
](url)

**Comment by qpmnguyen** [comment]
Thank you very much for your issue @mm3875!

Unfortunately, this discrepancy is due to lags between the state's public reporting dashboard and information that goes into making this table. If you can check out the daily screenshots we have at New Hampshire here (https://covidtracking.com/data/state/new-hampshire#historical), you can see that the state frequently updates new tests past our 4 pm EST publish time, where at certain points even until the early am the next day. 
This means that we often capture these increases later down the line as the state dashboard catches up. 
We are working on a solution internally to patch these numbers in based on this information provided by the state. 

Hope this helps!
