### ISSUE TITLE
[ND] PCL Historicals and WS2

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#522]
Deaths include several different data points, such as _"deaths due to COVID-19", "deaths where COVID-19 is not the primary cause", and "pending death records"._ We should consider "deaths due to COVID-19" as confirmed, and add the remaining values - **"pending death records", "deaths where COVID-19 is not the primary cause" and "deaths of individuals presumed positive" to obtain probables.** In WS2, we're reporting the total - number of individuals who tested positive and died from any cause while infected with COVID-19 - as our confirmed value. We should only be reporting "deaths due to covid-19" as our confirmed.

**Comment by jesseandersonumd** [comment]
5/12 Started reporting deaths and confirmed cases of deaths as the same value
5/31 Started separating confirmed and probable deaths

**Comment by jesseandersonumd** [comment]
5/12 CTP Started reporting deaths and confirmed cases of deaths as the same value
5/31 CTP Started separating confirmed and probable deaths

**Comment by muamichali** [comment]
ND started separating confirmed and probable deaths on 5/3. All the values from 5/3 until 5/31 need to be filled in from screenshots.

![image](https://user-images.githubusercontent.com/1749380/86149786-74905e80-baca-11ea-8d38-b936333341d8.png)

**Comment by karaschechtman** [comment]
**New decision for how to track COVID-19 deaths in ND**
Confirmed = due to COVID-19
Probable = presumed positive
Lumped = due to COVID-19 + presumed positive

**Comment by karaschechtman** [comment]
Edited tooltips and worksheet 2 values
**Probable**
<img width="229" alt="Screen Shot 2020-07-01 at 11 37 54 AM" src="https://user-images.githubusercontent.com/15933271/86263970-e5e61500-bb8f-11ea-8771-4df9c3e46dd8.png">
**Confirmed**
<img width="268" alt="Screen Shot 2020-07-01 at 11 37 48 AM" src="https://user-images.githubusercontent.com/15933271/86263977-e8486f00-bb8f-11ea-8aa9-b628bb2eb0ec.png">
**Lumped**
<img width="258" alt="Screen Shot 2020-07-01 at 11 37 41 AM" src="https://user-images.githubusercontent.com/15933271/86264014-f7c7b800-bb8f-11ea-917a-f4a73861f5a4.png">

**Comment by karaschechtman** [comment]
From [5/3 ](https://covidtracking.com/screenshots/ND/ND-20200503-121530.png)to [5/27](url), ND provided 3 categories in its table: “Deaths due to COVID-19”, “not the primary cause”, and “pending death records”. It did not provide probables

Changing "totals" to equal "Confirmed" to equal "Deaths Due to COVID-19", and zeroing out probables.

**Before (with @muamichali's prior edits in line with our old ND definitions):**
<img width="1088" alt="Screen Shot 2020-07-01 at 12 01 36 PM" src="https://user-images.githubusercontent.com/15933271/86267075-26e02880-bb94-11ea-83e4-13db45a2c7aa.png">
<img width="1184" alt="Screen Shot 2020-07-01 at 12 02 04 PM" src="https://user-images.githubusercontent.com/15933271/86267080-28a9ec00-bb94-11ea-91ab-5f7c8b2165a0.png">

**After**
<img width="1181" alt="Screen Shot 2020-07-01 at 12 11 27 PM" src="https://user-images.githubusercontent.com/15933271/86267047-1af46680-bb94-11ea-833b-c42a10071e9e.png">

**Comment by karaschechtman** [comment]
As a result of the revision for 5/3-5/27, it will appear as if deaths drop on 5/3 from 24 to 16, as we are excluding the pending + non-primary cause confirmed cases from our "Confirmed" and "Total" column. For 5/2 and prior, we have no way of excluding those numbers, because ND doesn't provide the breakdown.
<img width="557" alt="Screen Shot 2020-07-01 at 12 13 46 PM" src="https://user-images.githubusercontent.com/15933271/86267268-73c3ff00-bb94-11ea-92ab-8518ba8ce277.png">

Adding a public note to explain this:
"On 5/3, ND began providing counts of deaths for lab-confirmed individuals with death records still pending, and lab-confirmed individuals who died but not due to COVID. We exclude these numbers from our death counts, resulting in a drop from 24 deaths on 5/2 to 16 on 5/3."

**Comment by karaschechtman** [comment]
From [5/27](https://covidtracking.com/screenshots/ND/ND-20200527-124625.png) onward, changing values from screenshots so that:
Confirmed = due to COVID-19
Probable = presumed positive
Lumped = due to COVID-19 + presumed positive

**Before**
<img width="988" alt="Screen Shot 2020-07-01 at 12 24 20 PM" src="https://user-images.githubusercontent.com/15933271/86268748-a2db7000-bb96-11ea-84d0-bf9455eee1bb.png">

**Comment by karaschechtman** [comment]
Will need to make a public note: "On 6/18, CO revised down its confirmed death count from 66 to 64."
<img width="705" alt="Screen Shot 2020-07-01 at 12 57 39 PM" src="https://user-images.githubusercontent.com/15933271/86271180-76c1ee00-bb9a-11ea-8d1b-3e846e8da155.png">
