### ISSUE TITLE
[MS] data entry mistake from 7/8

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#586]
**State or US**: MS

**Describe the problem**
In the "Total Tests (PCR)" column, it seems that the last checker recorded the total tests number that lumps PCR and antibody tests instead of recording just the total PCR tests number. I'm changing it to just total PCR tests, so the number is lower. 
https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1594239073454000?thread_ts=1594238963.452000&cid=CUQ4MMTPD

**Link to data source**

**Comment by qpmnguyen** [comment]
Before: 
![image](https://user-images.githubusercontent.com/25627274/86971203-beb6b700-c13e-11ea-8cd0-43093475a89b.png)
After:
![image](https://user-images.githubusercontent.com/25627274/86971406-1d7c3080-c13f-11ea-80f5-82c7bf682b37.png)
Since total tests did not change from 7/6 to 7/7, carrying over negatives from 7/6
