### ISSUE TITLE
[ID] PCL Cases Historical

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#597]
ID has been reporting probables alongside confirmed cases via their dashboard since inception.
On States Daily, we have been tracking Positives but not Positive Cases (PCR) for all dates. To find these numbers, one needs to hover over the dashboard graphs for numbers from each day. We should check to see to see if we can backfill this data.
<img width="1372" alt="Screen Shot 2020-07-23 at 10 11 44 AM" src="https://user-images.githubusercontent.com/66738237/88296613-eecc9100-cccc-11ea-84cc-3b5d28a4626f.png">

**Comment by camille-le** [comment]
Hey @pscsharon, I was able to download a data export from the dashboard with data for  **new confirmed cases** and **new probable cases** by day.  

Attached is a modified spreadsheet with calculated cumulative data: [CTP_State_Total_Cases_Display_(2)_Full_Data_data.xlsx](https://github.com/COVID19Tracking/issues/files/4910341/CTP_State_Total_Cases_Display_.2._Full_Data_data.xlsx). 
* The first tab contains modified columns/calculations (in purple) which we can update **Positive Cases (PCR)** and **Positive** 
* The second tab contains the raw data export (unmodified) for future reference

**Comment by jaclyde** [comment]
Extended the time series for Confirmed and Probable cases using the source above, also replaced our Cases (confirmed plus probable) time series from March 14, 2020 to April 28, 2020 to better align with the Confirmed and Probable breakdowns (differences were minor less than 100 a day, likely caused by small backfilling by the state and/or time or sourcing differences). Negatives were not updated because the state draws their total tests from Total PCR Tests (People) not Positive+Negative, and it's a low priority metric. 

Values updated: 
[Changes (19).txt](https://github.com/COVID19Tracking/issues/files/6353612/Changes.19.txt)
