### ISSUE TITLE
MI: Data quality grade update

### ISSUE THREAD

**Issue by rmontroy** [COVID19Tracking/issues#60]
MDHHS is reporting negative test numbers again as of today.

**Comment by catawbasam** [comment]
Michigan is not being updated according to the covid19tracking web page because it is reporting specimens rather than people tested.   I urge you to report the specimen counts (with caveats) for the following reasons:  
1.	Other states are very likely double-counting people who have been tested multiple times. 
2.	Michigan’s confirmed case count is close to the reported positive count, suggesting they are not systematically taking multiple specimens (e.g. nose and mouth) per person.
3.	Ramp up in total test capacity is important to track in its own right.

**Comment by schwartzadev** [comment]
This seems to have been resolved. See the [Michigan page](https://covidtracking.com/data/state/michigan/) on the site.

* The data grade is now a B, accounting for reporting negatives.
* The data is noted to be reporting "total specimens"
