### ISSUE TITLE
[AR] PCL Cases Historicals

### ISSUE THREAD

**Issue by pscsharon** [COVID19Tracking/issues#612]
Arkansas has been reporting Confirmed-Cases since Mar 27th when they started using the arcgis dashboard.  Different than other states, AR reported Confirmed-Cases only on their State website instead of the dashboard for a while.  Even up to the current day, AR uses the phrase "Total Cases" in its arcgis instead of "Confirmed Cases."  

Please backfill confirmed cases back through Mar 27th.  

Background:

Screenshots:
http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/AR/

WS2 instructions:
<img width="1299" alt="Screen Shot 2020-07-13 at 6 49 53 AM" src="https://user-images.githubusercontent.com/67423649/87313826-4c93f880-c4d7-11ea-946f-5f0e8e278269.png">

States' Daily:
<img width="1444" alt="Screen Shot 2020-07-13 at 6 49 24 AM" src="https://user-images.githubusercontent.com/67423649/87313836-5289d980-c4d7-11ea-9ffb-4e9007e66b45.png">

**Comment by pscsharon** [comment]
Mar 27th screenshots from archive:

<img width="1242" alt="Screen Shot 2020-07-13 at 7 07 30 AM" src="https://user-images.githubusercontent.com/67423649/87314057-941a8480-c4d7-11ea-9483-05b6cf137013.png">
<img width="860" alt="Screen Shot 2020-07-13 at 7 07 39 AM" src="https://user-images.githubusercontent.com/67423649/87314067-97157500-c4d7-11ea-9f9f-143a6b5b5f26.png">

**Comment by brianskli** [comment]
It was verified that AR always reported confirmed cases through screenshots. Numbers copied to column V on States Daily accordingly. A gap in confirmed cases website screenshots exists in mid- to late March after the rollout of a new dashboard, but it can be inferred that these numbers also refer to confirmed cases due to (1) a consistent time-series and (2) the website always mirroring the dashboard, and the website indicating that it reports only confirmed cases after the introduction of dual screenshots.
Before:
<img width="781" alt="Screen Shot 2020-07-20 at 10 57 16 AM" src="https://user-images.githubusercontent.com/66738237/87952952-6b1a6680-ca78-11ea-97e7-80d69da58723.png">
After:
<img width="775" alt="Screen Shot 2020-07-20 at 11 01 27 AM" src="https://user-images.githubusercontent.com/66738237/87952962-6ce42a00-ca78-11ea-994f-31bb23054c06.png">

**Comment by muamichali** [comment]
Double Checked. Nice work, Brian!
