### ISSUE TITLE
[MP] MP started publishing both specimens and total tested people

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/issues#627]
Plus, they now have a nice ArcGIS dashboard:
https://cnmichcc.maps.arcgis.com/apps/opsdashboard/index.html#/4061b674fc964efe84f7774b7979d2b5

And a time series to back it: https://services8.arcgis.com/zkkZCub5I6ydvXQj/ArcGIS/rest/services/Coronavirus_PublicDashboardView/FeatureServer/3

There are only 3 values for Total People Tested, it looks to be a weekly metric.
Their testing numbers are also lagging, but they carry over the values.

**Comment by space-buzzer** [comment]
[mp_data_20200714.txt](https://github.com/COVID19Tracking/issues/files/4921824/mp_data_20200714.txt)

**Comment by space-buzzer** [comment]
Worksheet: https://docs.google.com/spreadsheets/d/1U1MLiRLWjv54BfEceoEpJuEQvtACuhOTTRJK4XIbZj8/edit#gid=1467795880
Updated testing numbers look good, the overall is not different then what we've been capturing, but the curve is smoother now.
*Total tested people*, looks like it's updated ~weekly, there are only 3 values. It makes *negatives* calculation hard

**Comment by space-buzzer** [comment]
[MP - Analysis #627 Clearing Negatives.pdf](https://github.com/COVID19Tracking/issues/files/4955969/MP.-.Analysis.627.Clearing.Negatives.pdf)

**Comment by muamichali** [comment]
Since our API still calculates total tests as pos+neg in MP, backfilling the total tests (people and tests) would require us to adjust the daily numbers of negative tests using mixed units throughout the time series. Therefore, we are not going to perform this backfill. MP does provide a timeseries through their [arcgis layer](https://services8.arcgis.com/zkkZCub5I6ydvXQj/ArcGIS/rest/services/Coronavirus_PublicDashboardView/FeatureServer/2/query), which is reflected in our avocado database which we plan to publish on GitHub shortly.
