### ISSUE TITLE
[OR] 6/15 Incorrect Hospitalization Value

### ISSUE THREAD

**Issue by the-daniel-lin** [COVID19Tracking/issues#631]
"In Oregon the hospital/ICU/Vent counts are missing for Monday 6/15. This is provided (M-F) on Oregon's "Daily Update" PDF. You can get there by using the "Primary Source" you guys already have: 

https://govstatus.egov.com/OR-OHA-COVID-19 

... then click "+ Additional Data and Projections" 
... then click "COVID-19 Daily Update" 
... which links to this PDF: 
https://www.oregon.gov/oha/PH/DISEASESCONDITIONS/DISEASESAZ/Emerging%20Respitory%20Infections/Oregon-COVID-19-Daily-Upda… 

THANKS SO MUCH for coordinating this effort! This has been a HUGE help!"

I was unable to find ICU/Vent values from screenshots/wayback, but we do have a screenshot from 6/15 that shows an updated Hospitalization value -- 899 (not 875).
![image](https://user-images.githubusercontent.com/67408226/87575920-7c80fe80-c685-11ea-8425-32aaa3c405c2.png)

Current CTP Data:
![image](https://user-images.githubusercontent.com/67408226/87576011-991d3680-c685-11ea-8cdd-6ed8e01ae69e.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_266z5)

**Comment by terwilliger42** [comment]
I'm the original submitter of that support ticket.  Here's the Oregon Health Authority's report from that day -- which has all of the values (vent, hospital, icu, etc).

[20200615.pdf](https://github.com/COVID19Tracking/issues/files/4926953/20200615.pdf)

**Comment by terwilliger42** [comment]
If you don't find that trustworthy, then you can also get that same PDF directly from Oregon Health Authority:

https://www.oregon.gov/oha/PH/DISEASESCONDITIONS/DISEASESAZ/Emerging%20Respitory%20Infections/Oregon-COVID-19-Update-06-15-2020-FINAL.pdf

**Comment by MattHilliard** [comment]
@terwilliger42 Thank you so much for reporting this and following up to link to this data. Oregon is a tough state for us to record correctly because of the weekday/weekend reporting differences. Looking at this, I am pretty sure we have other days we can fix with these state reports. I'm not sure if they've always been there and I just hadn't seen them, but I personally have done cleanup work based on their textual press releases; these seem much better. Anyway, I will open a follow-up issue to investigate that possibility. Meanwhile, I've fixed our hospitalization data for 6/15:

Before:
![image](https://user-images.githubusercontent.com/404503/87610840-7108f400-c6d4-11ea-8f71-281aa4fd10c3.png)

After:
![image](https://user-images.githubusercontent.com/404503/87610885-9a298480-c6d4-11ea-8458-a9fae1b10ed6.png)

This report can also be used to update our `Positive Cases (PCR)` and `Total PCR Tests` columns for 6/15 (previously they were unchanged that day).

Before:
![image](https://user-images.githubusercontent.com/404503/87611267-9813f580-c6d5-11ea-9701-2cc28f22f3f9.png)

After:
![image](https://user-images.githubusercontent.com/404503/87611294-b11ca680-c6d5-11ea-810a-2e01682210f6.png)
