### ISSUE TITLE
[OK] 6/28 Incorrect Total Cases

### ISSUE THREAD

**Issue by schmian** [COVID19Tracking/issues#634]
"Hello and thank you for the service you are doing. I spend a lot of time every day on your site while doing about 10 hours of research daily on the pandemic.

I noticed a small error, probably a typo, in the Oklahoma data for yesterday 28 June. The State reported 302 new cases and 12,944 total cases. The numbers are listed as 352 and 12,994 respectively in your Oklahoma listing."

This can also be confirmed in the screenshots from 6/28: https://covidtracking.com/screenshots/OK/OK-20200628-184700.png

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2672p)

**Comment by MattHilliard** [comment]
Agree it looks like a simple typo, 12994 instead of 12944.

Before:
![image](https://user-images.githubusercontent.com/404503/87608650-7d8a4e00-c6ce-11ea-80af-11444ab2efa7.png)

After:
![image](https://user-images.githubusercontent.com/404503/87608709-9b57b300-c6ce-11ea-86cc-5976a4120409.png)

I also notice that our "Positive Cases (PCR)" column was not changed that day even though it otherwise tracks OK positives exactly. I believe this was an oversight and so corrected this as well:

Before:
![image](https://user-images.githubusercontent.com/404503/87608964-3ea8c800-c6cf-11ea-8457-c60f7a458118.png)

After:
![image](https://user-images.githubusercontent.com/404503/87608984-49635d00-c6cf-11ea-9f4b-c0c4cebeff3f.png)
