### ISSUE TITLE
[OK] Page updated after Pub Shift 7/21

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#663]
**Describe Issue**
On 7/21 the OK page did not update before we published. They updated later that evening and we caught it in our last screenshot. We need to patch cases, deaths, and recoveries.

**Data Source**
Screenshot from 6:21 pm on 6/21
![OK-20200721-182114](https://user-images.githubusercontent.com/68712382/88337179-41756f80-cd04-11ea-98a7-b7bb5f693945.png)

**Comment by the-daniel-lin** [comment]
BEFORE: 
![image](https://user-images.githubusercontent.com/67408226/88394972-2e4eb800-cd75-11ea-8e88-5b19397d0d51.png)

AFTER:
![image](https://user-images.githubusercontent.com/67408226/88396174-06f8ea80-cd77-11ea-9357-546de7769241.png)

Also noticed that we had three 7/20's in a row. Since the values changed in other columns, I changed these dates to be 7/20, 7/21, 7/22

BEFORE:
![image](https://user-images.githubusercontent.com/67408226/88396605-9e5e3d80-cd77-11ea-93f4-974d721c3a55.png)

AFTER:
![image](https://user-images.githubusercontent.com/67408226/88396713-c483dd80-cd77-11ea-9bf5-f606f0647daf.png)

**Comment by the-daniel-lin** [comment]
BEFORE:
![image](https://user-images.githubusercontent.com/67408226/88400954-f13af380-cd7d-11ea-8772-ad8927385226.png)

Noticed that there were three consecutive 7/20's, and they had updated values for each. Changed them to 7/20, 7/21, 7/22, accordingly.

AFTER:
![image](https://user-images.githubusercontent.com/67408226/88401783-07957f00-cd7f-11ea-92eb-d75eecfeae13.png)
