### ISSUE TITLE
Arizona `negativeIncrease` is incorrectly identified

### ISSUE THREAD

**Issue by rgerkin** [COVID19Tracking/issues#671]
**State or US**: Arizona

**Describe the problem**
Your API is currently using data like [this](https://covidtracking.com/screenshots/AZ/AZ-20200723-180514.png) and  reporting `positiveIncrease` to be the "number of new cases reported today", and `negativeIncrease` to be the number of new PCR tests minus `positiveIncrease`.  But this is invalid because the former includes **PCR and serology** tests, while the latter includes **only PCR** tests.  The correct value to use for `negativeIncrease` would be "Number of new tests reported today" which is higher since it includes serology tests.  Then at least `positiveIncrease` and `negativeIncrease` would be reporting from the same collection of tests (i.e. both PCR and serology).  Coincidentally, the fraction positive by PCR and by serology in Arizona happens to be similar at this time, due to the past and current trajectory of the epidemic.  Hopefully in the future the Arizona website will offer a daily breakdown of PCR+ and PCR- tests, but at this time they only offer the daily total of PCR tests (and of serology tests), and then the weekly breakdown on a different section of the website (see "Laboratory Testing" in the link below).

**Link to data source**
Site: https://www.azdhs.gov/preparedness/epidemiology-disease-control/infectious-disease-epidemiology/covid-19/dashboards/index.php
Screenshot example: https://covidtracking.com/screenshots/AZ/AZ-20200723-180514.png

**Comment by rgerkin** [comment]
If someone would point me to the actual scraping code for Arizona, I would be happy to submit a PR to fix this.

**Comment by muamichali** [comment]
HI @rgerkin 

We do not use scrapers to capture the data. We use actual humans that visit the websites daily. 

Typically our positive number in Arizona includes both probable and confirmed cases, but we also separately publish in our API the number of PCR lab confirmed cases. This is slightly complicated by the fact that as of 7/18 Arizona no longer provides the breakdown of probable vs. confirmed cases via a hover-over action on their dashboard. 

We do not include antibody tests as part of the totals. We capture them separately, and plan to publish them in the future.

**Comment by rgerkin** [comment]
@muamichali Thank you. Their diligent work is appreciated.

Do you agree though that Arizona's `positiveIncrease` column contains people counted by methods other than PCR+, and that consequently the `negativeIncrease`, computed by difference, contains fewer than the actual number of PCR- people?

If you would prefer to exclude serology from the `positiveIncrease` and `negativeIncrease` numbers, then you should just null both of them for now.  Otherwise you get a big overestimate of % positive in downstream trackers using the API.

**Comment by muamichali** [comment]
Hi again @rgerkin

Thank you for your kind words.

API consumers can use PCR-only fields in our API (positiveCasesViral, totalTestsViral) _when available from the states_ to calculate percent positive rate.

Since the number of probable cases in AZ is very small compared to the overall number of cases (as far as we can tell from when they still reported the number until 7/18) it does not result in skewing the PPR significantly.

We are aware of the fact that probable cases are included in the overall cases as I mentioned above & we are working to remove them (https://github.com/COVID19Tracking/issues/issues/578). Working with 56 different data sets from the different jurisdictions and within a mostly volunteer organization means that changes are not always immediate.

Regarding the suggestion to lump serology tests and cases for calculating the percent positive rate, we published a blog post about this topic recently: https://covidtracking.com/blog/antibody-data-reporting

@rgerkin: We also have a scraper that fetches data from states that enables an extra level of checks in addition to the human checkers. If you would like to contribute your PR to that effort, we would really appreciate it.
https://github.com/COVID19Tracking/covid19-datafetcher

**Comment by rgerkin** [comment]
@muamichali Thanks for the clarification.  The reason I noticed the issue in the first place was that the % positive rates reported on the state website in one week bins (under the "Laboratory Testing" icon) were lower than those obtained from `positiveIncrease / (positiveIncrease + negativeIncrease)` using the API.  Part of that must have been the (small) fraction of probable-but-not-tested cases under `positiveIncrease`, but I realize now that another part was the difference between % positive by date-of-collection (reported in one week bins on the state website) and % positive by date of report (media reported and sort-of-computable from the API), which is big difference in a place with rapidly changing rates.  Since you found that the fraction of probable cases was small (when it was being reported), I think I'm happy to not worry too much about it.
