### ISSUE TITLE
[NH] PCL Historicals and Data Definitions

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#726]
**State or US**: New Hampshire

**Describe the problem**
5/13 Positive Cases is lower than surrounding days
Screenshots definitions for positives alternate between "presumptive-positive and CDC confirmed" and "CDC confirmed" only (e.g. 5/10-13), requiring review, especially before 4/29

**Link to data source**
https://www.nh.gov/covid19/
http://covid-tracking-project-data.s3-website.us-east-1.amazonaws.com/state_screenshots/NH/

**Comment by MattHilliard** [comment]
![image](https://user-images.githubusercontent.com/404503/92979150-cad13480-f45f-11ea-90be-30471c3d68f6.png)
Spent a while looking at this. Some preliminary conclusions:
* The 5/13 and 5/14 numbers for Positive Cases (PCR) are clearly not from the same dataset. In the screenshot, the 5/13 positive cases (PCR) number (1863) is the number of "current cases" (e.g. unrecovered) which seems like a data entry error. I don't know where the 5/14 number comes from; it's not in the screenshot.
* Positive Cases (PCR) data is missing from 5/10 through 5/12 for no apparent reason
* Besides the gap and the two weird days, Positive Cases (PCR) is identical to our Positives column where available.
* NH provides a dataset for "positive cases by report date" that has data slightly revised from what was posted on their dashboard. It nevertheless tracks very closely with our positives column:
![image](https://user-images.githubusercontent.com/404503/92978673-75485800-f45e-11ea-9330-0e70b85b8b59.png)
* In contrast to what @brianskli wrote a month ago, the "presumptive positive" language seems present until 5/16 when it becomes just "positive". "Presumptive-positive" sounds weird, like it could mean probable, but the transition to simpler confirmed language doesn't involve any decline. I think the "presumptive" language may just be referring to the fact it's not the CDC itself confirming the case, which is fine.

Under these circumstances, I think ideally we would use the official NH data for both Positive Cases (PCR) and Positives, but our backfill policy is not to take revised data like this since it's not "forward compatible" with future data entry.

Given that, I think the right thing to do is repair and extend the Positive Cases (PCR) column by copying over the data from Positives going all the way back to early March. Since it so closely tracks the state confirmed positive case data I think we can conclude the dashboard was reporting confirmed positives throughout.

**Comment by MattHilliard** [comment]
Small note, looks like the 5/14 number came from a "Weekly Report" that data entry was using for hospitalization numbers. Unfortunately this was an old value from more than a week prior, but after the mistake the previous day, perhaps it seemed plausible since it was an increase.

**Comment by MattHilliard** [comment]
After discussion on the backfill team, we decided to be conservative and repair the clearly incorrect data from 5/10 through 5/15 in the Positive Cases (PCR) column but not copy the longer history of the Positives column.

Before:
![image](https://user-images.githubusercontent.com/404503/94994593-946e6d00-0566-11eb-97a3-e844405d0030.png)

After:
![image](https://user-images.githubusercontent.com/404503/94994604-aa7c2d80-0566-11eb-903e-af9a7717b522.png)
