### ISSUE TITLE
[Unknown States] Some Deaths(confirmed) values before 5/11 got deleted

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#731]
**State or US**:  Unknown States

**Describe the problem**
Some cells in the Deaths (confirmed) column were relying on a formula from the Checks tab. When the Checks tab was purged, it caused some of the values in Deaths Confirmed column to be impacted.

**Comment by space-buzzer** [comment]
I'll take over this issue to handle all bad refs and formula investigations in States Daily.
#734 is another instance

**Comment by space-buzzer** [comment]
In the most recent version of States Daily.
We have `REF`s only in KY `Total Tests (PCR) `

All the `REF`s are part of formulas (or bad formulas).

We have formulas in other places too, some are numeric (e.g., `=3684+101`) which should be fine and stable, others might not be as stable `=sum(C3258:D3258)`

**Comment by space-buzzer** [comment]
[formulas.csv.txt](https://github.com/COVID19Tracking/issues/files/5038158/formulas.csv.txt)

**Comment by space-buzzer** [comment]
This issue was originally opened for **KS** `Deaths (confirmed)` was a formula leading nowhere.
Now we have a few values in this column, instead of the formula. Did we ever have a confirmation that death count was confirmed deaths and then it got revised?
It happened with cases on May 7th -- Case count started including both confirmed and probable cases

**Comment by space-buzzer** [comment]
The 9 values for **KS** `Deaths (confirmed)` column (dates 3-11/May) are there by mistake. They were not deleted when confirmed vs probable death metrics were cleaned up prior to publishing these metrics in the API because it was a formula, and the cells looked empty. Earlier this week, the cells were re-filled with a value, but it should actually remain empty.
![Screenshot from 2020-08-06 23-39-13](https://user-images.githubusercontent.com/62236447/89617082-6ad2e700-d83e-11ea-954f-78f0fbf96d7e.png)
![Screenshot from 2020-08-06 23-41-30](https://user-images.githubusercontent.com/62236447/89617085-6b6b7d80-d83e-11ea-83fa-86774a24e02a.png)

**Comment by space-buzzer** [comment]
We have many states with this empty-formula turned to numbers between May 3rd to 11th.
All of them now got values in these cells, values that I think weren't supposed to be there, because they looked empty, so were skipped during the cleanup
