### ISSUE TITLE
[WY] Probables Backfill

### ISSUE THREAD

**Issue by jesseandersonumd** [COVID19Tracking/issues#739]
**State:** WY

**Dates impacted:** 4/29 - 7/27

**Issue description:** We started reporting probable cases on 7/28. The states probables can be calculated from total cases - confirmed cases. We can backfill these values back to 4/29. 

**Source:** https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/

**Comment by jesseandersonumd** [comment]
**BEFORE:** 
![Screen Shot 2020-08-06 at 9 27 01 AM](https://user-images.githubusercontent.com/57415941/89537219-03c61b80-d7c7-11ea-9533-460ceef8b45b.png)

**Comment by jesseandersonumd** [comment]
**AFTER:** 
![Screen Shot 2020-08-06 at 10 10 47 AM](https://user-images.githubusercontent.com/57415941/89542028-20655200-d7cd-11ea-9139-c657e286c741.png)

**Comment by whobody** [comment]
We found some discrepancies in Positive Cases (PCR) and Probables. We also found Probables that were not filled out prior to May. The plan is as follows:

1. Backfill Positive Cases (PCR) for all dates 4/8 - 5/13 due to being a day off or having some small discrepancies. 

2. Fix Positives Cases (PCR) for 5/16, 5/18, 5/19, 5/21, 5/24, 5/25 due to discrepancies and duplicates.

3. Backfill probables from 4/8 - 4/30 for dates we did not collect. 

4. Fix probables for  5/1 - 5/4, 5/8, 5/9, 5/11, 5/13, 5/16, 5/18, 5/19, 5/21, 5/24, 5/25, 5/27, 6/2, 6/15, 6/24, 7/6, 7/13

**Comment by muamichali** [comment]
[Probable Timeseries Backfill WY.xlsx](https://github.com/COVID19Tracking/issues/files/5308459/Probable.Timeseries.Backfill.WY.xlsx)
