### ISSUE TITLE
[NE] Backfill Total PCR Tests (People) to 3/27

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#743]
**State or US**: NE 

**Describe the problem**
From 8/12 outreach (https://covid-tracking.slack.com/archives/C010RFJ0ZD3/p1597273411010100), we have confirmed that NE reports total test units in people. Using screenshots, we can backfill Total PCR Tests (People) through 3/27.

**Link to data source**
State screenshots

Screenshot from 3/27 for reference:
https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/NE/NE-20200327-161027.png

**Comment by the-daniel-lin** [comment]
Our NE data should be as of the previous day, however, as I began backfilling, I noticed that testing values were lagged by two days.

It turns out that on 5/14, we have positive and negative values from 5/13 (correct!), but we logged the 5/12 testing value (incorrect) -- it's weird because this thread from 5/12 shows them using the correct numbers: https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1589312845314300?thread_ts=1589312845.314300, but somehow, that value got shifted

I'm lumping this fix in with this issue, correcting Total PCR Test (People) from **49799** to **53427** and moving **49799** to 5/13 and **48019** to 5/12. Then, I'll backfill through 3/27. 

All values are taken from state screenshots

**Comment by the-daniel-lin** [comment]
BEFORE 5/12 - 5/14 CORRECTION:
![image](https://user-images.githubusercontent.com/67408226/90652575-0d9e4480-e1f3-11ea-814e-8eca38cf24b0.png)

AFTER 5/12 - 5/14 CORRECTION:
![image](https://user-images.githubusercontent.com/67408226/90652747-42aa9700-e1f3-11ea-932b-42e313b9e702.png)

**Comment by the-daniel-lin** [comment]
BEFORE BACKFILL:

![image](https://user-images.githubusercontent.com/67408226/90652937-74236280-e1f3-11ea-831d-46bc36282be9.png)

AFTER BACKFILL:

![image](https://user-images.githubusercontent.com/67408226/90668425-f1a39e80-e204-11ea-9d83-2138cab85d82.png)
