### ISSUE TITLE
[NH] 8/20 Antibody SVP input incorrect

### ISSUE THREAD

**Issue by brianskli** [COVID19Tracking/issues#785]
**State or US**: New Hampshire

**Describe the problem**
On 8/20, numbers meant for Total Antibody Tests was added to Total Antibody Test (People). The value should be copied into Total Antibody Tests on States Daily.

**Link to data source**
https://www.nh.gov/covid19/index.htm

**Comment by the-daniel-lin** [comment]
This issue was partially resolved here: https://github.com/COVID19Tracking/issues/issues/780. I will adjust the 8/20 Total Antibody Tests (People) value (28924) to reflect the corresponding screenshot value from 8/20.

https://covid-tracking-project-data.s3.us-east-1.amazonaws.com/state_screenshots/NH/NH-20200820-181947.png

**Comment by the-daniel-lin** [comment]
BEFORE:
![image](https://user-images.githubusercontent.com/67408226/92938589-9464cc80-f401-11ea-8317-3bcf2842f070.png)

AFTER:
![image](https://user-images.githubusercontent.com/67408226/92938714-c9711f00-f401-11ea-81c2-2081434d1ad9.png)
