### ISSUE TITLE
[AR] Back-fill antigen and probable cases numbers starting 9/3

### ISSUE THREAD

**Issue by muamichali** [COVID19Tracking/issues#816]
**State or US**:  Arkansas 

**Describe the problem**
Starting 9/3 Arkansas started providing the information about Total Antigen Tests, Positive Antigen Tests, Negative Antigen Tests 
and Probable Cases. This is to backfill the information from those days. 

**Link to data source**
Upload PDFs here please

**Comment by karaschechtman** [comment]
**September 3:**
<img width="699" alt="Screen Shot 2020-09-07 at 2 49 28 PM" src="https://user-images.githubusercontent.com/15933271/92412325-80774d00-f119-11ea-9795-d4821a4516b6.png">

**September 4:**
<img width="798" alt="Screen Shot 2020-09-07 at 2 49 48 PM" src="https://user-images.githubusercontent.com/15933271/92412340-8a994b80-f119-11ea-9b0f-5417e041892e.png">

**September 5:**
<img width="771" alt="Screen Shot 2020-09-07 at 2 50 06 PM" src="https://user-images.githubusercontent.com/15933271/92412350-9127c300-f119-11ea-977a-dd4d520dffba.png">

We should also backfill back to 6/11 using the values provided in the chart

**Comment by karaschechtman** [comment]
**Before**
<img width="206" alt="Screen Shot 2020-09-07 at 4 23 56 PM" src="https://user-images.githubusercontent.com/15933271/92415363-8fb0c780-f126-11ea-9c8d-fc1cac3a6018.png">
**After**
Note: It looks like the totals were consistently backfilled for 9/1 and 9/2 (and 9/3 and 9/4) resulting in different deltas in each day of the report. I used the least recent deltas from 9/3 to make the math work so that the numbers for 6/11-8/31 would sum to the subtraction/keep the timeseries continuous, and to get closest to the "date reported" meaning. 

For flat line data before 8/31: Because the time ranges represent **all** the testing done that range, I think we can only associate them with the last day of each range onward instead of applying it to the beginning of the range. This gets us back to 7/31 rather than 6/11.

9/2 = 13631 - 533 = 13098
9/1 = 13098 - 590 = 12508
8/31 = 7090 + 5418 = 12508
7/31 - 8/30 = 7090
<img width="178" alt="Screen Shot 2020-09-07 at 4 36 10 PM" src="https://user-images.githubusercontent.com/15933271/92415711-41042d00-f128-11ea-8afd-67afb8138dce.png">

**Comment by karaschechtman** [comment]
**Positive and negative**

Applying the same principles of applying updates only from the last day of the range onward and using the deltas from the 9/3 screenshot.

**Before**
<img width="240" alt="Screen Shot 2020-09-07 at 4 41 32 PM" src="https://user-images.githubusercontent.com/15933271/92415942-1d8db200-f129-11ea-81fb-5e4e16b5b821.png">

**After**
negative calculations
9/2 = 11522 - 474 = 11048
9/1 = 11048 - 434 = 10614
8/31 = 6005+4609 = 10614
7/31 - 8/30 = 6005

positive calculations
9/2 = 2109 - 59 = 2050
9/1 = 2050 - 156 = 1894
8/31 = 1085+809 = 1894
7/31 - 8/30 = 1085

<img width="237" alt="Screen Shot 2020-09-07 at 4 46 20 PM" src="https://user-images.githubusercontent.com/15933271/92416057-ad336080-f129-11ea-9085-3bcd96aeae8a.png">

**Comment by karaschechtman** [comment]
**Probable Cases**
_also affects totals and confirmed (since we want to grab them from the PDF). resulted in overriding yesterday's confirmed value_

9/5
<img width="581" alt="Screen Shot 2020-09-07 at 5 05 01 PM" src="https://user-images.githubusercontent.com/15933271/92416685-b3770c00-f12c-11ea-9d51-983b0467c38f.png">

9/4
<img width="578" alt="Screen Shot 2020-09-07 at 5 06 28 PM" src="https://user-images.githubusercontent.com/15933271/92416698-c1c52800-f12c-11ea-873d-8c29f31f3980.png">

9/3
<img width="598" alt="Screen Shot 2020-09-07 at 5 07 59 PM" src="https://user-images.githubusercontent.com/15933271/92416707-c984cc80-f12c-11ea-80d6-c1a537bf3f9f.png">

**Before**
<img width="713" alt="Screen Shot 2020-09-07 at 5 11 53 PM" src="https://user-images.githubusercontent.com/15933271/92416803-40ba6080-f12d-11ea-9358-0c7989b01df9.png">

**After**
<img width="705" alt="Screen Shot 2020-09-07 at 5 16 02 PM" src="https://user-images.githubusercontent.com/15933271/92416960-d5bd5980-f12d-11ea-92ac-3e2edab2a6ab.png">
