### ISSUE TITLE
[WI] We were lumping their currently hospitalized w/ pending 

### ISSUE THREAD

**Issue by whobody** [COVID19Tracking/issues#865]
**State or US**: 
WI

**Describe the problem**
We were lumping their pending into currently hospitalized from roughly 4/2 - 6/9. 

We also have some incorrect values throughout our time series, that became obvious when we received a time series directly from [Wisconsin Hospital Assoc website](https://www.wha.org/COVID19Update). 

**Link to data source**
https://www.wha.org/COVID19Update
[Patients_|_Total_per_Day_data-2 2.xlsx](https://github.com/COVID19Tracking/issues/files/5278879/Patients_._Total_per_Day_data-2.2.xlsx)

This has been backfilled by Rebma. 

Someone, please tell me all the ways I messed this GH issue up.

**Comment by space-buzzer** [comment]
WIs hospitalization data had holes between 2020-07-29 - 2020-07-22, we filled it from our previously captured values (looks like 2 sharp drops, probably due to partial data after new HHS guidelines re hospitalizations).

![Screenshot from 2020-09-24 13-01-44](https://user-images.githubusercontent.com/62236447/94194474-977ea480-fe66-11ea-8044-bf2d7eeea581.png)
![Screenshot from 2020-09-24 13-04-41](https://user-images.githubusercontent.com/62236447/94194476-98173b00-fe66-11ea-8145-d0cfc4d7ba4c.png)
![Screenshot from 2020-09-24 13-04-52](https://user-images.githubusercontent.com/62236447/94194479-98afd180-fe66-11ea-8f46-1161153a7166.png)
