### ISSUE TITLE
MT: Negatives reports are lower on Mar 29 than on Mar 30

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/issues#89]
MT reports a lower total on March 30 than March 29 (3961 v 4143), even though they also provide a good number of tests. Since negative = total - positive, that results in a negative number of negatives, then the totalTestResultsIncrease goes negative as well.

(TBH the MT numbers on their website are confusing to me. The screen shots show totals that don't jibe with the "new tests completed" figures right above them. Maybe they're just updating the new tests every time they refresh the page?)

**Comment by karaschechtman** [comment]
Hi @Jmuccigr,
Thank you for pointing this out. It is common for states' reports on their total tests lag updates on their positive tests, making it appear as if negative numbers are decreasing (since negatives are inferred through totals - positives). This lag is, I think, what you are noticing about MT's "Total Number of Tests Completed" figure sometimes appearing mismatched to their "Total Cases." 

We operate on a policy of never decreasing the number of negatives day over day. Thus, in this case, we carried over the negative figure from 3/29, 4143, to 3/30 until total test updates caught up with positives on 3/31.
<img width="257" alt="Screen Shot 2020-05-20 at 9 28 47 AM" src="https://user-images.githubusercontent.com/15933271/82451685-558abf80-9a7c-11ea-85f7-b1c248c7989d.png">
