### ISSUE TITLE
[OR] Backfill 10/8 Data

### ISSUE THREAD

**Issue by hmhoffman** [COVID19Tracking/issues#893]
**State:** OR

**Dates Affected:** 10/8

**Describe the issue:** On 10/8, OR did not update in time for our publish. We should patch data from screencaps. 

**Links:** https://covid-tracking.slack.com/archives/CUQ4MMTPD/p1602196821017200

**Comment by MattHilliard** [comment]
Updated most columns from screenshots. Not available in screenshots: `Hospitalized - currently`, `In ICU - currently`, and `On Ventilator - currently`. Maybe for the same reason they updated late, there's no "data report" for 10/8 either, so as far as I know there's no way to recover the current hospitalization metrics.

Note OR isn't providing `Recovered` so that doesn't change even with normal data entry. `Probable cases` is calculated by subtracting `Positive Cases (PCR)` from `Positives`.

Relevant screenshots:
- https://covidtracking.com/screenshots/OR/OR-20201009-002909.png
- https://covidtracking.com/screenshots/OR/OR-secondary-20201009-002920.png
- https://covidtracking.com/screenshots/OR/OR-tertiary-20201009-002933.png

Before:
![image](https://user-images.githubusercontent.com/404503/95686580-b7cf9280-0bcc-11eb-8f8f-dc9c20fd449a.png)

After:
![image](https://user-images.githubusercontent.com/404503/95686810-59a3af00-0bce-11eb-80d6-aa05251185fa.png)
