### ISSUE TITLE
DE: Negatives fixed? Count updated but grade and state dash haven't

### ISSUE THREAD

**Issue by catawbasam** [COVID19Tracking/issues#90]
I have friends working to improve the Delaware situation, and want let them know whether the state has implemented regular reporting of negative test results. 

This morning I see a higher negatives count for Delaware on covid19tracking, but the grade remains 'C' and I see no state-reported negative count at https://coronavirus.delaware.gov/

Could you clarify the situation?

**Comment by una-smith** [comment]
Hi.  The new negatives count follows a contact I made yesterday with the Delaware Department of Public Health Call Center.  Here is the response I received from DPH Call Center:

> Due to the number of private test being administered, we do not have an accurate count of those being tested until numbers are reported to DPH. This number is only reported once a week. We will pass your feedback along to the web team, however.

I would like to see the COVID19Tracking dashboard updated.  A "B" grade seems appropriate and the comment mentioning no negatives since 3/13 should be updated.

**Comment by una-smith** [comment]
Now 4/1 and DE has improved reporting of negative test counts but the COVIDTracking dashboard still says about DE

> Last reported negative number is from 3/13 News Report.

Someone please remove that sentence!

**Comment by realfuture** [comment]
We’re on it! It just changed last night, and we have to manually update grades and notes (for now).

Alexis
