### ISSUE TITLE
MI: Latent data updates

### ISSUE THREAD

**Issue by saewoonam** [COVID19Tracking/issues#97]
The values for Saturday March 28th are not correct.   They are just the daily figures from the previous day.

**Comment by karaschechtman** [comment]
Hi @saewoonam,
Thanks for bringing this to our attention. We've since backfilled the MI data for 3/28 so this issue is no longer relevant. However, this lag was likely due to the data for MI updating after our publication cutoff. We publish the daily stats every afternoon. If a state updates the number of tests or cases after that time, we catch that update on the following day.
