### ISSUE TITLE
[OR] Switch total tests from Total PCR tests (people) to Total PCR tests (specimens)

### ISSUE THREAD

**Issue by jaclyde** [COVID19Tracking/issues#997]
State: Oregon:

Issue: Oregon has stopped reporting Total, positive, and negative PCR tests (people) and started reporting Total PCR tests (specimens) as well as positive and negative PCR tests (specimens). We hope to get a time series from the state soon to backfill Total PCR tests (specimens

**Comment by karaschechtman** [comment]
[Changes (5).txt](https://github.com/COVID19Tracking/issues/files/5646279/Changes.5.txt)

**Comment by space-buzzer** [comment]
[Multi-edit tool-PRODUCTION - OR-reb-20201210.csv.txt](https://github.com/COVID19Tracking/issues/files/5669530/Multi-edit.tool-PRODUCTION.-.OR-reb-20201210.csv.txt)
[Multi-edit tool-PRODUCTION - OR-reb-20201210_post.csv.txt](https://github.com/COVID19Tracking/issues/files/5669531/Multi-edit.tool-PRODUCTION.-.OR-reb-20201210_post.csv.txt)

**Comment by space-buzzer** [comment]
In addition to backfilling specimens time series, we're also cleaning up the `Total PCR Tests (People)` field since Oregon stopped reporting it.

[Multi-edit tool-PRODUCTION - OR-reb-20201210_cleanup.csv.txt](https://github.com/COVID19Tracking/issues/files/5669579/Multi-edit.tool-PRODUCTION.-.OR-reb-20201210_cleanup.csv.txt)
[Multi-edit tool-PRODUCTION - OR-reb-20201210_cleanup.post.csv.txt](https://github.com/COVID19Tracking/issues/files/5669581/Multi-edit.tool-PRODUCTION.-.OR-reb-20201210_cleanup.post.csv.txt)
